[package]
name = "similarity"
version = "0.0.0"
edition = "2021"
default-run = "similarity"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
env_logger = "0.11.5"
image = "0.25.2"
indicatif = "0.17.8"
indicatif-log-bridge = "0.2.2"
log = "0.4.22"
